<div style="background-color: rgb(231, 231, 188); left: 248px; top: 222px; display: none;" id="translate_popup">
	<table class="translate_links"><tbody><tr><td valign="top">
		<a lang="en" title="English" href="#" xml:lang="en" class="languagelink"><img width="16" height="11" alt="English" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag en"> English</a>
		<a lang="ar" title="Arabic" href="#" xml:lang="ar" class="languagelink"><img width="16" height="11" alt="العربية" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag ar"> العربية</a>
		<a lang="bg" title="Bulgarian" href="#" xml:lang="bg" class="languagelink"><img width="16" height="11" alt="български" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag bg"> български</a>
		<a lang="de" title="German" href="#" xml:lang="de" class="languagelink"><img width="16" height="11" alt="Deutsch" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag de"> Deutsch</a>
		<a lang="el" title="Greek" href="#" xml:lang="el" class="languagelink"><img width="16" height="11" alt="ελληνική" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag el"> ελληνική</a>
		<a lang="es" title="Spanish" href="#" xml:lang="es" class="languagelink"><img width="16" height="11" alt="español" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag es"> español</a>
		<a lang="fa" title="Persian" href="#" xml:lang="fa" class="languagelink"><img width="16" height="11" alt="فارسی" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag fa"> فارسی</a>
		<a lang="fi" title="Finnish" href="#" xml:lang="fi" class="languagelink"><img width="16" height="11" alt="suomi" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag fi"> suomi</a>
		<a lang="fr" title="French" href="#" xml:lang="fr" class="languagelink"><img width="16" height="11" alt="français" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag fr"> français</a>
		<a lang="he" title="Hebrew" href="#" xml:lang="he" class="languagelink"><img width="16" height="11" alt="עברית" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag he"> עברית</a>
		<a lang="hi" title="Hindi" href="#" xml:lang="hi" class="languagelink"><img width="16" height="11" alt="हिन्दी" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag hi"> हिन्दी</a>
	</td><td valign="top">
		<a lang="hu" title="Hungarian" href="#" xml:lang="hu" class="languagelink"><img width="16" height="11" alt="magyar" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag hu"> magyar</a>
		<a lang="id" title="Indonesian" href="#" xml:lang="id" class="languagelink"><img width="16" height="11" alt="bahasa Indonesia" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag id"> bahasa Indonesia</a>
		<a lang="it" title="Italian" href="#" xml:lang="it" class="languagelink"><img width="16" height="11" alt="italiano" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag it"> italiano</a>
		<a lang="ja" title="Japanese" href="#" xml:lang="ja" class="languagelink"><img width="16" height="11" alt="日本語" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag ja"> 日本語</a>
		<a lang="ko" title="Korean" href="#" xml:lang="ko" class="languagelink"><img width="16" height="11" alt="한국어" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag ko"> 한국어</a>
		<a lang="ms" title="Malay" href="#" xml:lang="ms" class="languagelink"><img width="16" height="11" alt="bahasa Melayu" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag ms"> bahasa Melayu</a>
		<a lang="nl" title="Dutch" href="#" xml:lang="nl" class="languagelink"><img width="16" height="11" alt="Nederlands" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag nl"> Nederlands</a>
		<a lang="no" title="Norwegian" href="#" xml:lang="no" class="languagelink"><img width="16" height="11" alt="norsk" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag no"> norsk</a>
		<a lang="pl" title="Polish" href="#" xml:lang="pl" class="languagelink"><img width="16" height="11" alt="polski" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag pl"> polski</a>
		<a lang="pt" title="Portuguese" href="#" xml:lang="pt" class="languagelink"><img width="16" height="11" alt="português" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag pt"> português</a>
		<a lang="ro" title="Romanian" href="#" xml:lang="ro" class="languagelink"><img width="16" height="11" alt="română" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag ro"> română</a>
	</td><td valign="top">
		<a lang="ru" title="Russian" href="#" xml:lang="ru" class="languagelink"><img width="16" height="11" alt="русский" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag ru"> русский</a>
		<a lang="sq" title="Albanian" href="#" xml:lang="sq" class="languagelink"><img width="16" height="11" alt="shqipe" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag sq"> shqipe</a>
		<a lang="sr" title="Serbian" href="#" xml:lang="sr" class="languagelink"><img width="16" height="11" alt="српски" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag sr"> српски</a>
		<a lang="th" title="Thai" href="#" xml:lang="th" class="languagelink"><img width="16" height="11" alt="ภาษาไทย" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag th"> ภาษาไทย</a>
		<a lang="tr" title="Turkish" href="#" xml:lang="tr" class="languagelink"><img width="16" height="11" alt="Türkçe" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag tr"> Türkçe</a>
		<a lang="vi" title="Vietnamese" href="#" xml:lang="vi" class="languagelink"><img width="16" height="11" alt="tiếng Việt" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag vi"> tiếng Việt</a>
		<a lang="zh-cn" title="Chinese (Simplified)" href="#" xml:lang="zh-cn" class="languagelink"><img width="16" height="11" alt="中文 (简体)" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag zh-cn"> 中文 (简体)</a>
		<a lang="zh-tw" title="Chinese (Traditional)" href="#" xml:lang="zh-tw" class="languagelink"><img width="16" height="11" alt="中文 (繁體)" src="http://simos.info/blog/wp-content/plugins/google-ajax-translation/transparent.gif" class="translate_flag zh-tw"> 中文 (繁體)</a>
		<a title="translate page" href="http://translate.google.com/translate?sl=auto&amp;tl=en&amp;u=simos.info/blog/" rel="nofollow" class="google_branding">powered by<img width="51" height="15" title="" alt="Google" src="http://www.google.com/uds/css/small-logo.png"></a>
	</td></tr></tbody></table>
</div>